# Generated by Django 5.0.3 on 2024-03-24 22:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='originalImage',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default='media/image/DJI_0030.jpg', upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='numberOfColors',
            field=models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(8)]),
        ),
    ]
