# Generated by Django 5.0.3 on 2024-03-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_remove_image_originalimage_image_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="simplifiedImage",
        ),
        migrations.AddField(
            model_name="image",
            name="processed_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="processed_images/"
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(upload_to="image/"),
        ),
    ]
