# Generated by Django 5.0.3 on 2024-04-09 22:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_remove_image_simplifiedimage_image_processed_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="color1",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="color2",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="color3",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="color4",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="color5",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="color6",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="color7",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="color8",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
