# Generated by Django 5.0.3 on 2024-04-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_image_color1_image_color2_image_color3_image_color4_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookCovers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bookImage", models.ImageField(upload_to="kaggle_images/")),
            ],
        ),
    ]
